### ISSUE TITLE
Doctests no longer build with default features

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/AEADs#755]
This was somehow introduced in #752 which bumped `aead` to v0.6.0-rc.4, but I am baffled as to how or what's even happening.

## Example reproduction

```console
$ cd aes-gcm
$ cargo test --doc
[...]
---- aes-gcm/src/lib.rs - (line 150) stdout ----
error[E0432]: unresolved import `aes_gcm::aead::Generate`
  --> aes-gcm/src/lib.rs:156:28
   |
8  |     aead::{Aead, AeadCore, Generate, Key, KeyInit},
   |                            ^^^^^^^^ no `Generate` in the root
   |
note: found an item that was configured out
```

## Notes

This occurs in several crates, any of which use this style of gating:

```rust
#![cfg_attr(feature = "getrandom", doc = "```")]
#![cfg_attr(not(feature = "getrandom"), doc = "```ignore")]
```

Curiously, if the first line is changed to:

```rust
#![cfg_attr(feature = "getrandom", doc = "```ignore")]
```

Then the test is successfully ignored, suggesting this gating somehow isn't working correctly:

```
running 2 tests
test aes-gcm/src/lib.rs - (line 150) ... ignored
test aes-gcm/src/lib.rs - (line 189) ... ignored
```

Note the other example, which depends on both the `arrayvec` and `getrandom` features, *is* successfully being ignored with logic like:

```rust
#![cfg_attr(all(feature = "getrandom", feature = "arrayvec"), doc = "```")]
#![cfg_attr(
    not(all(feature = "getrandom", feature = "arrayvec")),
    doc = "```ignore"
)]
```

Perhaps the weirdest part is nothing in #752 actually changed how this gating worked, it just started behaving differently when the `aead` crate was upgraded from v0.6.0-rc.3 to v0.6.0-rc.4.

**Comment by eligrubb** [comment]
The issue appears to stem from the `Generate` trait, which the `aead` crate began publicly exporting with `v0.6.0-rc.4` and [is gated by the `rand_core` feature](https://github.com/RustCrypto/traits/blob/b4f864c093cfcb9276e72490aa6fc3e95a4c0c2a/aead/src/lib.rs#L26). This feature is not always simultaneously enabled with the `getrandom` feature, and the rustdocs tests show what happen.

## Potential fixes

### Option A: AEADs level fix

Each AEAD can make their individual `getrandom` feature imply `rand_crypto` - PR #833 does this. Requires changes to every crate, but fix is at this level

### Option B: Upstream dependency fix

The `aead` trait itself can have the `aead/getrandom` feature imply `aead/rand_crypto`. [traits PR#2450](https://github.com/RustCrypto/traits/pull/2450) does this. No code changes, does require bumping `aead` version that AEADs crate depends on.

### Option C: Upstream code fix

Make the `Generate` trait either gated behind the `aead/getrandom` feature instead, or exported crate-wide for `aead`.

 ## Why workspace `cargo test` worked despite this

 `aes-siv` and `ascon-aead128` depend on aead without default-features = false and aead's default = ["rand_core"]. In a full cargo test --workspace run, the single shared aead build gets rand_core from those members, leaking `Generate` into every crate's doctest. Which is why the failures only surface when running a tests for individual crates.
